#:schema node_modules/wrangler/config-schema.json
name = "snap-web"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[env.production]
name = "snap-web"

[env.preview]
name = "snap-web-preview"

# Performance optimizations
[limits]
memory = 128
cpu_ms = 50
